name: Build vue project and deploy to the server

on:
  push:
    branches:
      - prod
      - main #记得删除
  pull_request:
    types:
      - closed
    branches:
      - prod

jobs:
  deploy:
    name: Deploy the nodejs project to the server
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/cache@v2
        with:
          path: '**/node_modules'
          key: ${{ runner.os }}-modules-${{ hashFiles('**/yarn.lock') }}
      - name: install dependencies
        run: yarn
      - name: build project
        run: yarn build
      - name: Deploy to the PROD server
        uses: easingthemes/ssh-deploy@main
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_KEY }}
          ARGS: '-avzr --delete'
          SOURCE: 'dist/'
          REMOTE_HOST: ${{ secrets.SERVER_IP }}
          REMOTE_USER: ${{ secrets.SERVER_USER }}
          REMOTE_PORT: ${{ secrets.SSH_PORT }}
          TARGET: ${{ secrets.SERVER_PROD_PATH }}
          EXCLUDE: "/404.html/, /.htaccess/, /.user.ini/"
